### ISSUE TITLE
Roxy Capture throws error when JSON has {"error" in File

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic-community/roxy#838]
#### The issue
When doing a capture on a json file that has {"error" the capture throws an error:

ERROR: 757: unexpected token at '--6b6ca738438591c5
Content-Type: application/json
X-Primitive: object-node()
X-URI: /swagger-ui/create/example-swagger.json

{"swagger":"2.0", "info":{"title":"eVISOR Health Opportun
...
:"memberIdentifier"}}}}
--6b6ca738438591c5--
''
ERROR: ["C:/Users/rkenne10/ProdReadiness/roxy/deploy/lib/json/common.rb:148:in `
parse'", "C:/Users/rkenne10/ProdReadiness/roxy/deploy/lib/json/common.rb:148:in
`parse'", "C:/Users/rkenne10/ProdReadiness/roxy/deploy/lib/server_config.rb:2713
:in `execute_query_8'", "C:/Users/rkenne10/ProdReadiness/roxy/deploy/lib/server_
config.rb:564:in `execute_query'", "C:/Users/rkenne10/ProdReadiness/roxy/deploy/
lib/server_config.rb:1962:in `block in save_files_to_fs'", "C:/Users/rkenne10/Pr
odReadiness/roxy/deploy/lib/server_config.rb:1959:in `each'", "C:/Users/rkenne10
/ProdReadiness/roxy/deploy/lib/server_config.rb:1959:in `save_files_to_fs'", "C:
/Users/rkenne10/ProdReadiness/roxy/deploy/lib/server_config.rb:1754:in `capture'
", "deploy/lib/ml.rb:166:in `<main>'"]

I believe it should be using an http status code or something other than the body of the response to determine if an error occurred.

Your business use case. How much time would this save you? Can you currently work around this missing feature?
We do a capture of modules database for every prod deployment.

Timeframe : How urgently do you feel you need this RFE addressed? Why?
We would like it fairly soon. We have a workout to disable the raise exception line
    # raise ExitException.new(JSON.pretty_generate(JSON.parse(r.body))) if r.body.match(/\{"error"/)

What are the steps to reproduce the problem?
1. Create JSON file with {"error".... in database
2. Run ml <env> capture

#### Tech Specs

Which Operating System are you using?
Windows 7
Which version of MarkLogic are you using?
8.0-6.1
Which version of Roxy are you using (see version.txt)?
1.7.7

**Comment by grtjn** [comment]
I'll tag it with customer-request to give it some priority..

**Comment by grtjn** [comment]
I took a closer look, and skipping that line is really the right thing to do here. The http call to /v1/eval will return a 500 at errors, which already raises an exception at an earlier stage.

I also checked against ML7, and the issue does not occur at all there. It makes use of different logic, which does not trip over this..
